spring:
  profiles:
    active: dev
server:
  port: 4001
spring:
  profiles: dev
  application:
         name: jlm-config-dev
server:
  port: 4002
spring:
  profiles: prod
  application:
         name: jlm-config-prod
